addons:
  apt:
    packages:
      - sshpass

cache:
  directories:
    - "$HOME/.m2/repository/"
    - "$HOME/src/main/resources/static/"
    - "$HOME/dist/"

stages:
  - frontend
  - backend
  - deploy
  - patch

jobs:
  include:
    - stage: frontend
      language: node_js
      node_js:
        - "10"
      install: 
        - npm install
      script: 
        - npm test
      after_success: 
        - npm run dist
      
    - stage: backend
      language: java
      jdk: openjdk8
      script:
        - mvn install jacoco:report -Dmaven.repo.local=.m2/repository --batch-mode
      after_success:
        - mvn sonar:sonar -Dsonar.projectKey=seogi1004_vuejs-springboot-starter -Dsonar.organization=seogi1004-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

    - stage: deploy
      language: java
      jdk: openjdk8
      script:
        - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      after_success:
        - ls -all ./dist
        - sshpass -V
        - export SSHPASS=$SSH_PASSWORD
        # SSH 포트가 22가 아니라면 -P 옵션을 줄것
        - sshpass -e scp -r -oStrictHostKeyChecking=no ./dist/vuejs-springboot-starter-$POM_VERSION.jar root@180.228.199.230:/opt/

    - stage: patch
      language: java
      jdk: openjdk8
      before_script:
        # pom.xml이 변경되지 않았다면 프로세스를 종료함
        - |
          if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep 'pom.xml'
          then
            echo "Not running CI since only docs were changed."
            exit
          fi
      script:
        - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        - echo $POM_VERSION
      after_success:
        - git config --global user.name "alvin.h"
        - git config --global user.email "seogi777@gmail.com"
        - git checkout $TRAVIS_BRANCH
        - git remote remove origin
        - git remote add origin https://seogi1004:$GIT_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
        - git tag -a $POM_VERSION -m "Version created by gitlab-ci Build"
        - git push origin --tags
